from typing import List, Optional
from pydantic import BaseModel, Field


class TranscriptRequest(BaseModel):
    url_or_id: str = Field(
        ...,
        description="YouTube video URL (standard, shortened, shorts, embed) or raw 11-character video ID",
        examples=["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ"]
    )
    languages: Optional[List[str]] = Field(
        default=["en", "en-US", "en-GB"],
        description="Preferred language codes in order of priority",
        examples=[["en", "en-US"]]
    )
    preserve_formatting: bool = Field(
        default=False,
        description="Whether to preserve HTML entity formatting from captions"
    )


class TranscriptSegment(BaseModel):
    text: str = Field(..., description="Caption text for this segment")
    start: float = Field(..., description="Start offset in seconds")
    duration: float = Field(..., description="Duration in seconds")
    timestamp_str: str = Field(..., description="Human-readable timestamp (MM:SS or HH:MM:SS)", examples=["02:45"])


class TranscriptResponse(BaseModel):
    video_id: str = Field(..., description="11-character YouTube video ID")
    language: str = Field(..., description="Language name of the fetched transcript", examples=["English (auto-generated)"])
    language_code: str = Field(..., description="Language code of the fetched transcript", examples=["en"])
    is_generated: bool = Field(..., description="Whether the transcript was auto-generated by YouTube")
    is_translatable: bool = Field(default=False, description="Whether the transcript can be translated")
    total_duration_seconds: float = Field(..., description="Total estimated video duration in seconds")
    total_duration_str: str = Field(..., description="Formatted total duration (e.g. 10:24)", examples=["10:24"])
    word_count: int = Field(..., description="Total number of words in the transcript")
    segment_count: int = Field(..., description="Total number of caption segments")
    segments: List[TranscriptSegment] = Field(..., description="List of caption segments with timestamps")
    full_text: str = Field(..., description="Full concatenated plain text transcript")


class TranscriptErrorResponse(BaseModel):
    error: str = Field(..., description="Error category or type")
    detail: str = Field(..., description="Detailed explanation of the failure")
    video_id: Optional[str] = Field(default=None, description="Extracted video ID if available")
